#!/usr/bin/python

class autos:
    def __init__(self, arrivalTime, velocity, id):
    	self.arrivalTime = arrivalTime
    	self.velocity = velocity		#randomly decided speed
    	self.id = id					#ID number/index, determined when auto spawns. Eastbound even, Westbound odd

    def calculate_auto_delay(self):
    	#triggered on the YELLOW traffic signal in safety_signals class. Find two conditions:
	    #Its back end will be past the farthest edge of the crosswalk in YELLOW seconds.
	    #Its front end will have not reached the near edge of the crosswalk in (YELLOW + RED) seconds. 
		#If both of these conditions are false, the auto will be delayed; otherwise the auto is not delayed at the crosswalk. 