#!/usr/bin/python

class crosswalksignal(ENUM):
    NO_WALK = 0
    WALK = 1

class trafficlight(ENUM):
    RED = 0
    YELLOW = 1
    GREEN = 2

class safety_signals:
    def __init__(self, crosswalk_signal, traffic_signal, timer):
        self.crosswalk_signal = crosswalksignal(crosswalk_signal) #WALK || NO_WALK
        self.traffic_signal = trafficsignal(traffic_light) #RED || YELLOW || GREEN

    #definitions for functions changing the safety signals
    def button_press(self):
        if self.traffic_signal is GREEN:
            #if green timer expired
                yellow_begins(self)
            #else
                #green timer decrementing so in rightmost blue state
        if self.traffic_signal is YELLOW:
            #trigger yellow timer = 8s

        if self.traffic_signal is RED:
            #if red timer not expired do nothing

        return self

    def calculate_auto_delay:

    def ped_at_button(self):
        if self.traffic_signal is RED
            #walk
        else
            button_press(self)

    def yellow_begins(self):
        self.traffic_signal = YELLOW
        #yellow timer = 8s
        return self

    def yellow_expires(self):
        self.crosswalk_signal = WALK
        self.traffic_signal = RED

    def red_expires(self):
        self.crosswalk_signal = NO_WALK
        self.traffic_signal = GREEN
        green_begins(self)
        return self

    def red_begins(self):
        self.crosswalk_signal = WALK
        # red timer = 18s: pedestians can walk
        return self

    def green_begins(self):
        self.traffic_signal = GREEN
        #green timer = 35s
        return self

    def green_expires(self):
        return self

    def calculate_ped_delay:


